web-name: Elegant Access
title: Elegant Access - Your Majesty
description: Elegant Access is a blog that share android know-how.
baseurl: "https://elegantaccess.org" # the subpath of your site, e.g. /blog
url: "https://elegantaccess.org" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    WaitZ
author-image:   C1.JPG
author-job:     Developer
author-email:
author-twitter:
author-linkedin:
author-link: eleg_aces
about-author:   I am a Android developer focusing on Kotlin and Jetpack Compose development. Always hungry to keep learning.

# Social settings
social-twitter:   intent/follow?screen_name=eleg_aces
social-facebook:  eleg.aces
social-github:    KuanChunChen
social-pinterest:
social-instagram: eleg.aces.kc
social-youtube: @WaitZshigoto
social-vk:
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: G-TS24BQ2JDT
google_ad_client: 5317402524376092
# Facebook App ID
facebook-appid: 374092904421484

# Comment Section (Disqus)
disqus-identifier: eleg_aces # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
  - jekyll-category-pages
languages: ["zh", "en", "ja"]
exclude_from_localizations: ["javascript", "images", "css", "search.json", "_includes", "tags"]
default_locale_in_subfolder: false

default_lang: zh 

paginate: 20
paginate_path: "/page/:num/"

include:
  - _pages
  - _site

sass:
  sass_dir: _sass
  style: compressed

future: true
timezone:	Asia/Taipei
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
